{% set name = "geodemo_zw" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b1d056d3b425eebc38b3ad17736ce49dceef9d37c875f8632d992ba87ce2e344

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api   
    - folium
    - ipyleaflet
    - pyshp
    - python >=3.6

test:
  imports:
    - geodemo_zw

about:
  home: "https://github.com/DataGeoranger/geodemo_zw"
  license: MIT
  license_family: MIT
  license_file: LICENSE 
  summary: "A geodeom from remote desktop"
  doc_url: https://datageoranger.github.io/geodemo_zw/
  dev_url: https://github.com/DataGeoranger/geodemo_zw

extra:
  recipe-maintainers:
    - DataGeoranger
